# Generated by Django 5.2.8 on 2025-11-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=400)),
                ('long_description', models.TextField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
