# Generated by GitHub Copilot on 2025-11-05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={
                'ordering': ['-is_featured', '-release_date', 'title'],
                'verbose_name': 'jogo',
                'verbose_name_plural': 'jogos',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='game',
            name='hero_image_upload',
            field=models.ImageField(blank=True, upload_to='games/hero/'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.CharField(blank=True, help_text='Lista separada por vírgula (ex.: PC, Xbox, PlayStation)', max_length=180),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('pre_production', 'Pré-produção'), ('in_development', 'Em desenvolvimento'), ('early_access', 'Acesso antecipado'), ('released', 'Lançado'), ('archived', 'Arquivado')], default='in_development', max_length=32),
        ),
        migrations.AddField(
            model_name='game',
            name='tagline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='trailer_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='cover_image_upload',
            field=models.ImageField(blank=True, upload_to='games/covers/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
    ]
