# Generated by Django 5.2.8 on 2025-11-07 01:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_enhancements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoria de FAQ',
                'verbose_name_plural': 'categorias de FAQ',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL alternativa para a arte de capa, caso não envie arquivo'),
        ),
        migrations.CreateModel(
            name='DonationPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('message', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('visibility', models.CharField(choices=[('private', 'Privado'), ('team_only', 'Visível para a equipe'), ('public', 'Pode ser exibido')], default='team_only', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_pledges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'promessa de doação',
                'verbose_name_plural': 'promessas de doação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=220)),
                ('answer', models.TextField()),
                ('audience', models.CharField(choices=[('community', 'Comunidade'), ('partners', 'Parceiros'), ('team', 'Equipe interna'), ('general', 'Geral')], default='general', max_length=32)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='games.faqcategory')),
            ],
            options={
                'verbose_name': 'pergunta frequente',
                'verbose_name_plural': 'perguntas frequentes',
                'ordering': ['category', 'order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('topic', models.CharField(choices=[('gameplay', 'Jogabilidade'), ('art_ui', 'Arte e interface'), ('technology', 'Tecnologia e performance'), ('community', 'Comunidade'), ('business', 'Parcerias e negócio'), ('other', 'Outro')], default='other', max_length=32)),
                ('message', models.TextField()),
                ('impact_rating', models.PositiveSmallIntegerField(default=3, help_text='Escala de 1 (baixo) a 5 (alto)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('new', 'Recebido'), ('in_review', 'Em análise'), ('acknowledged', 'Planejado'), ('published', 'Publicado')], default='new', max_length=24)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feedback da comunidade',
                'verbose_name_plural': 'feedbacks da comunidade',
                'ordering': ['-created_at'],
            },
        ),
    ]
