# Generated by Django 5.2.8 on 2025-11-07 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_faqcategory_alter_game_cover_image_donationpledge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpledge',
            name='pix_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationpledge',
            name='pix_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationpledge',
            name='pix_status',
            field=models.CharField(choices=[('pending', 'Aguardando Pix'), ('awaiting_confirmation', 'Comprovante enviado'), ('confirmed', 'Pix confirmado'), ('failed', 'Pagamento não localizado')], default='pending', max_length=24),
        ),
        migrations.AddField(
            model_name='donationpledge',
            name='pix_transaction_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='donationpledge',
            name='pix_txid',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verificação de e-mail',
                'verbose_name_plural': 'verificações de e-mail',
                'ordering': ['-created_at'],
            },
        ),
    ]
